// Sample data for demonstration when API is not available
const sampleProducts = [
    // SAREES
    {
        id: 1,
        name: "Elegant Banarasi Saree",
        price: 4999,
        originalPrice: 7999,
        image: "images/saree-banarasi.svg",
        category: "sarees",
        description: "Beautiful handwoven Banarasi saree with intricate gold work",
        colors: ["Red", "Blue", "Green"],
        sizes: ["Free Size"],
        inStock: true,
        rating: 4.5,
        reviews: 28
    },
    {
        id: 7,
        name: "Royal Kanjivaram Silk Saree",
        price: 8999,
        originalPrice: 12999,
        image: "images/saree-kanjivaram.svg",
        category: "sarees",
        description: "Authentic Kanjivaram silk saree with traditional motifs and rich zari border",
        colors: ["Deep Red", "Royal Blue", "Emerald Green"],
        sizes: ["Free Size"],
        inStock: true,
        rating: 4.8,
        reviews: 42
    },
    {
        id: 8,
        name: "Georgette Printed Saree",
        price: 2499,
        originalPrice: 3999,
        image: "images/saree-georgette.svg",
        category: "sarees",
        description: "Lightweight georgette saree with contemporary floral prints",
        colors: ["Pink", "Purple", "Teal"],
        sizes: ["Free Size"],
        inStock: true,
        rating: 4.3,
        reviews: 35
    },
    {
        id: 9,
        name: "Chiffon Designer Saree",
        price: 3799,
        originalPrice: 5499,
        image: "images/saree-chiffon.svg",
        category: "sarees",
        description: "Elegant chiffon saree with sequin work and beaded border",
        colors: ["Black", "Navy Blue", "Wine"],
        sizes: ["Free Size"],
        inStock: true,
        rating: 4.6,
        reviews: 28
    },
    {
        id: 10,
        name: "Cotton Handloom Saree",
        price: 1899,
        originalPrice: 2899,
        image: "images/saree-cotton.svg",
        category: "sarees",
        description: "Pure cotton handloom saree with traditional block prints",
        colors: ["White", "Cream", "Light Blue"],
        sizes: ["Free Size"],
        inStock: true,
        rating: 4.4,
        reviews: 56
    },
    {
        id: 11,
        name: "Organza Embroidered Saree",
        price: 6499,
        originalPrice: 9999,
        image: "images/saree-organza.svg",
        category: "sarees",
        description: "Luxury organza saree with delicate embroidery and pearl work",
        colors: ["Powder Blue", "Peach", "Lavender"],
        sizes: ["Free Size"],
        inStock: true,
        rating: 4.7,
        reviews: 31
    },
    {
        id: 12,
        name: "Tussar Silk Saree",
        price: 5299,
        originalPrice: 7599,
        image: "images/saree-tussar.svg",
        category: "sarees",
        description: "Natural tussar silk saree with handpainted madhubani art",
        colors: ["Golden Yellow", "Orange", "Rust"],
        sizes: ["Free Size"],
        inStock: true,
        rating: 4.5,
        reviews: 24
    },
    {
        id: 13,
        name: "Net Saree with Heavy Work",
        price: 4799,
        originalPrice: 7299,
        image: "images/saree-net.svg",
        category: "sarees",
        description: "Glamorous net saree with heavy stone and thread work",
        colors: ["Black", "Red", "Golden"],
        sizes: ["Free Size"],
        inStock: true,
        rating: 4.6,
        reviews: 39
    },

    // LEHENGAS
    {
        id: 20,
        name: "Royal Red Bridal Lehenga",
        price: 12999,
        originalPrice: 19999,
        image: "images/lehenga-royal-red.svg",
        category: "lehengas",
        description: "Stunning red bridal lehenga with heavy embroidery and gold work",
        colors: ["Red", "Maroon", "Deep Pink"],
        sizes: ["S", "M", "L", "XL"],
        inStock: true,
        rating: 4.9,
        reviews: 45
    },
    {
        id: 21,
        name: "Pink Floral Lehenga",
        price: 8999,
        originalPrice: 13999,
        image: "images/lehenga-pink-floral.svg",
        category: "lehengas",
        description: "Beautiful pink lehenga with floral embroidery and gota work",
        colors: ["Pink", "Peach", "Light Pink"],
        sizes: ["S", "M", "L", "XL"],
        inStock: true,
        rating: 4.6,
        reviews: 32
    },
    {
        id: 22,
        name: "Blue Net Designer Lehenga",
        price: 15999,
        originalPrice: 24999,
        image: "images/lehenga-blue-net.svg",
        category: "lehengas",
        description: "Designer blue net lehenga with sequin work and heavy dupatta",
        colors: ["Royal Blue", "Navy Blue", "Sky Blue"],
        sizes: ["S", "M", "L", "XL"],
        inStock: true,
        rating: 4.8,
        reviews: 28
    },
    {
        id: 2,
        name: "Designer Lehenga Choli",
        price: 15999,
        originalPrice: 22999,
        image: "https://images.unsplash.com/photo-1594736797933-d0401ba200fe?w=400",
        category: "lehengas",
        description: "Stunning designer lehenga with heavy embroidery work",
        colors: ["Pink", "Red", "Blue"],
        sizes: ["S", "M", "L", "XL"],
        inStock: true,
        rating: 4.8,
        reviews: 45
    },

    // KURTIS
    {
        id: 30,
        name: "Printed Cotton Kurti",
        price: 1899,
        originalPrice: 2999,
        image: "images/kurti-printed-cotton.svg",
        category: "kurtis",
        description: "Comfortable cotton kurti with beautiful prints perfect for daily wear",
        colors: ["Blue", "Green", "Yellow"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        inStock: true,
        rating: 4.3,
        reviews: 67
    },
    {
        id: 31,
        name: "Embroidered Cream Kurti",
        price: 2799,
        originalPrice: 4299,
        image: "images/kurti-embroidered.svg",
        category: "kurtis",
        description: "Elegant cream kurti with traditional embroidery and mirror work",
        colors: ["Cream", "Off White", "Light Beige"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        inStock: true,
        rating: 4.5,
        reviews: 54
    },
    {
        id: 3,
        name: "Cotton Kurti Set",
        price: 1299,
        originalPrice: 1899,
        image: "https://images.unsplash.com/photo-1583391733956-6c78276477e1?w=400",
        category: "kurtis",
        description: "Comfortable cotton kurti with palazzo pants",
        colors: ["White", "Yellow", "Pink"],
        sizes: ["S", "M", "L", "XL"],
        inStock: true,
        rating: 4.2,
        reviews: 67
    },
    {
        id: 32,
        name: "Silk Festive Kurti",
        price: 3499,
        originalPrice: 5499,
        image: "images/kurti-silk-festive.svg",
        category: "kurtis",
        description: "Premium silk kurti with gold border perfect for festivals",
        colors: ["Maroon", "Purple", "Teal"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        inStock: true,
        rating: 4.6,
        reviews: 43
    },

    // SUITS
    {
        id: 40,
        name: "Green Anarkali Suit",
        price: 4599,
        originalPrice: 7999,
        image: "images/suit-anarkali.svg",
        category: "suits",
        description: "Beautiful green Anarkali suit with dupatta perfect for special occasions",
        colors: ["Green", "Mint Green", "Emerald"],
        sizes: ["S", "M", "L", "XL"],
        inStock: true,
        rating: 4.7,
        reviews: 51
    },
    {
        id: 41,
        name: "Purple Sharara Suit",
        price: 6299,
        originalPrice: 9999,
        image: "images/suit-sharara.svg",
        category: "suits",
        description: "Elegant purple sharara suit with heavy embroidery and mirror work",
        colors: ["Purple", "Violet", "Lavender"],
        sizes: ["S", "M", "L", "XL"],
        inStock: true,
        rating: 4.8,
        reviews: 39
    },
    {
        id: 4,
        name: "Anarkali Suit",
        price: 3499,
        originalPrice: 4999,
        image: "https://images.unsplash.com/photo-1594736797933-d0401ba200fe?w=400",
        category: "suits",
        description: "Traditional Anarkali suit with dupatta",
        colors: ["Green", "Purple", "Orange"],
        sizes: ["S", "M", "L", "XL"],
        inStock: true,
        rating: 4.6,
        reviews: 33
    },
    {
        id: 6,
        name: "Embroidered Sharara",
        price: 5999,
        originalPrice: 8999,
        image: "https://images.unsplash.com/photo-1594736797933-d0401ba200fe?w=400",
        category: "suits",
        description: "Beautiful embroidered sharara with kurta",
        colors: ["Cream", "Pink", "Blue"],
        sizes: ["S", "M", "L", "XL"],
        inStock: true,
        rating: 4.7,
        reviews: 52
    },

    // ACCESSORIES
    {
        id: 50,
        name: "Gold Plated Jewelry Set",
        price: 3999,
        originalPrice: 6999,
        image: "images/accessory-jewelry-set.svg",
        category: "accessories",
        description: "Complete gold plated jewelry set with necklace, earrings, and bangles",
        colors: ["Gold", "Rose Gold", "Silver"],
        sizes: ["Free Size"],
        inStock: true,
        rating: 4.7,
        reviews: 73
    },
    {
        id: 51,
        name: "Designer Handbag",
        price: 2499,
        originalPrice: 3999,
        image: "images/accessory-handbag.svg",
        category: "accessories",
        description: "Premium leather designer handbag with multiple compartments",
        colors: ["Brown", "Black", "Tan"],
        sizes: ["Free Size"],
        inStock: true,
        rating: 4.5,
        reviews: 56
    },
    {
        id: 5,
        name: "Silk Dupatta",
        price: 899,
        originalPrice: 1299,
        image: "https://images.unsplash.com/photo-1583391733956-6c78276477e1?w=400",
        category: "accessories",
        description: "Pure silk dupatta with golden border",
        colors: ["Gold", "Silver", "Red"],
        sizes: ["Free Size"],
        inStock: true,
        rating: 4.3,
        reviews: 19
    },
    {
        id: 52,
        name: "Traditional Footwear",
        price: 1599,
        originalPrice: 2499,
        image: "images/accessory-footwear.svg",
        category: "accessories",
        description: "Comfortable traditional footwear with ethnic designs",
        colors: ["Gold", "Silver", "Bronze"],
        sizes: ["5", "6", "7", "8", "9"],
        inStock: true,
        rating: 4.3,
        reviews: 42
    }
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { sampleProducts };
}